In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("data2.csv")

In [3]:
X = df.drop(['Applied'],axis=1).values
y = df['Applied'].values

In [4]:
import sklearn

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42 ,stratify=y)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_predict
#b = StandardScaler()

#X2_train = b.fit_transform(X_train)
#X2_test = b.fit_transform(X_test)

steps = [('ss',StandardScaler()),('pca', PCA()),('logistic_regression', LogisticRegression())]

pipeline = Pipeline(steps)
pipeline.fit(X_train, y_train)

c2 = pipeline.score(X_test,y_test)

print c2

0.91


In [14]:
predictions = pipeline.predict(X_test)

In [15]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       0.94      0.94      0.94       145
          1       0.84      0.84      0.84        55

avg / total       0.91      0.91      0.91       200



In [16]:
print(confusion_matrix(y_test,predictions))

[[136   9]
 [  9  46]]


In [17]:
from sklearn.model_selection import cross_val_predict

predicted2 = cross_val_predict(pipeline, X_test, y_test, cv=10)
print sklearn.metrics.accuracy_score(y_test, predicted2) 

0.905


In [18]:
print(classification_report(y_test,predicted2))

             precision    recall  f1-score   support

          0       0.96      0.91      0.93       145
          1       0.79      0.89      0.84        55

avg / total       0.91      0.91      0.91       200



In [19]:
print(confusion_matrix(y_test,predicted2))

[[132  13]
 [  6  49]]


In [20]:
from sklearn.ensemble import GradientBoostingClassifier
steps2 = [('ss',StandardScaler()),('pca', PCA()),('GradientBoosterClassifier', GradientBoostingClassifier())]

pipeline2 = Pipeline(steps)
pipeline2.fit(X_train, y_train)

c2 = pipeline2.score(X_test,y_test)

print c2
#rj = GradientBoostingClassifier()

0.91


In [24]:
from sklearn.ensemble import VotingClassifier

eclf1 = VotingClassifier(estimators=[('lr', pipeline), ('gb', pipeline2)], voting='hard')
eclf1.fit(X_train,y_train)
c3 = eclf1.score(X_test,y_test)
prediction_ensemble = eclf1.predict(X_test)
print c3

0.91


In [25]:
print(classification_report(y_test,prediction_ensemble))

             precision    recall  f1-score   support

          0       0.94      0.94      0.94       145
          1       0.84      0.84      0.84        55

avg / total       0.91      0.91      0.91       200



In [26]:
print(confusion_matrix(y_test,prediction_ensemble))

[[136   9]
 [  9  46]]


In [28]:

from sklearn.externals import joblib
joblib.dump(eclf1, 'ensemble_GBC_LR.pkl')

['ensemble_GBC_LR.pkl']